/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_function_ianchang_libffmpeg_FFmpegUtils */

#ifndef _Included_com_function_ianchang_libffmpeg_FFmpegUtils
#define _Included_com_function_ianchang_libffmpeg_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_function_ianchang_libffmpeg_FFmpegUtils
 * Method:    testFFmpeg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_function_ianchang_libffmpeg_FFmpegUtils_testFFmpeg
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
