/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_function_ianchang_simplemvp_detector_DetectorManager */

#ifndef _Included_com_function_ianchang_simplemvp_detector_DetectorManager
#define _Included_com_function_ianchang_simplemvp_detector_DetectorManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_function_ianchang_simplemvp_detector_DetectorManager
 * Method:    initModel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_function_ianchang_simplemvp_detector_DetectorManager_initModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_function_ianchang_simplemvp_detector_DetectorManager
 * Method:    landMarks
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_function_ianchang_simplemvp_detector_DetectorManager_landMarks
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
