package com.function.ianchang.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.function.ianchang.simplegreendao.PageInfo;
import com.function.ianchang.simplegreendao.UserInfo;
import com.function.ianchang.simplegreendao.ScheduleInfo;
import com.function.ianchang.simplegreendao.ActivityInfo;

import com.function.ianchang.dao.PageInfoDao;
import com.function.ianchang.dao.UserInfoDao;
import com.function.ianchang.dao.ScheduleInfoDao;
import com.function.ianchang.dao.ActivityInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pageInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig scheduleInfoDaoConfig;
    private final DaoConfig activityInfoDaoConfig;

    private final PageInfoDao pageInfoDao;
    private final UserInfoDao userInfoDao;
    private final ScheduleInfoDao scheduleInfoDao;
    private final ActivityInfoDao activityInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pageInfoDaoConfig = daoConfigMap.get(PageInfoDao.class).clone();
        pageInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        scheduleInfoDaoConfig = daoConfigMap.get(ScheduleInfoDao.class).clone();
        scheduleInfoDaoConfig.initIdentityScope(type);

        activityInfoDaoConfig = daoConfigMap.get(ActivityInfoDao.class).clone();
        activityInfoDaoConfig.initIdentityScope(type);

        pageInfoDao = new PageInfoDao(pageInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        scheduleInfoDao = new ScheduleInfoDao(scheduleInfoDaoConfig, this);
        activityInfoDao = new ActivityInfoDao(activityInfoDaoConfig, this);

        registerDao(PageInfo.class, pageInfoDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(ScheduleInfo.class, scheduleInfoDao);
        registerDao(ActivityInfo.class, activityInfoDao);
    }
    
    public void clear() {
        pageInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        scheduleInfoDaoConfig.clearIdentityScope();
        activityInfoDaoConfig.clearIdentityScope();
    }

    public PageInfoDao getPageInfoDao() {
        return pageInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ScheduleInfoDao getScheduleInfoDao() {
        return scheduleInfoDao;
    }

    public ActivityInfoDao getActivityInfoDao() {
        return activityInfoDao;
    }

}
